using System;
using System.Collections.Generic;
using System.Text;

namespace FitnessTool
{
    public class AfcdFoodEntryRaw
    {

        public string publicFoodKey { get; set; } = "";
        public string classificationID { get; set; } = "";
        public string derivation { get; set; } = "";
        public string foodName { get; set; } = "";
        public FoodClassification foodClassification { get; set; } = null!;

        public decimal? energyWithDietaryFibreEquatedKj { get; set; }
        public decimal? energyWithoutDietaryFibreEquatedKj { get; set; }
        public decimal? moistureG { get; set; }
        public decimal? proteinG { get; set; }
        public decimal? nitrogenG { get; set; }
        public decimal? fatTotalG { get; set; }
        public decimal? ashG { get; set; }
        public decimal? totalDietaryFibreG { get; set; }
        public decimal? alcoholG { get; set; }
        public decimal? fructoseG { get; set; }
        public decimal? glucoseG { get; set; }
        public decimal? sucroseG { get; set; }
        public decimal? maltoseG { get; set; }
        public decimal? lactoseG { get; set; }
        public decimal? galactoseG { get; set; }
        public decimal? totalSugarsG { get; set; }
        public decimal? addedSugarsG { get; set; }
        public decimal? freeSugarsG { get; set; }
        public decimal? starchG { get; set; }
        public decimal? dextrinG { get; set; }
        public decimal? glycerolG { get; set; }
        public decimal? glycogenG { get; set; }
        public decimal? inulinG { get; set; }
        public decimal? erythritolG { get; set; }
        public decimal? maltitolG { get; set; }
        public decimal? mannitolG { get; set; }
        public decimal? xylitolG { get; set; }
        public decimal? maltodextrinG { get; set; }
        public decimal? oligosaccharidesG { get; set; }
        public decimal? polydextroseG { get; set; }
        public decimal? raffinoseG { get; set; }
        public decimal? stachyoseG { get; set; }
        public decimal? sorbitolG { get; set; }
        public decimal? resistantStarchG { get; set; }
        public decimal? availableCarbohydrateWithoutSugarAlcoholsG { get; set; }
        public decimal? availableCarbohydrateWithSugarAlcoholsG { get; set; }

        public decimal? aceticAcidG { get; set; }
        public decimal? citricAcidG { get; set; }
        public decimal? fumaricAcidG { get; set; }
        public decimal? lacticAcidG { get; set; }
        public decimal? malicAcidG { get; set; }
        public decimal? oxalicAcidG { get; set; }
        public decimal? propionicAcidG { get; set; }
        public decimal? quinicAcidG { get; set; }
        public decimal? shikimicAcidG { get; set; }
        public decimal? succinicAcidG { get; set; }
        public decimal? tartaricAcidG { get; set; }

        public decimal? aluminiumAlMcg { get; set; }
        public decimal? antimonySbMcg { get; set; }
        public decimal? arsenicAsMcg { get; set; }
        public decimal? cadmiumCdMcg { get; set; }
        public decimal? calciumCaMg { get; set; }
        public decimal? chromiumCrMcg { get; set; }
        public decimal? chlorideClMg { get; set; }
        public decimal? cobaltCoMcg { get; set; }
        public decimal? copperCuMg { get; set; }
        public decimal? fluorideFMcg { get; set; }
        public decimal? iodineIMcg { get; set; }
        public decimal? ironFeMg { get; set; }
        public decimal? leadPbMcg { get; set; }
        public decimal? magnesiumMgMg { get; set; }
        public decimal? manganeseMnMg { get; set; }
        public decimal? mercuryHgMcg { get; set; }
        public decimal? molybdenumMoMcg { get; set; }
        public decimal? nickelNiMcg { get; set; }
        public decimal? phosphorusPMg { get; set; }
        public decimal? potassiumKMg { get; set; }
        public decimal? seleniumSeMcg { get; set; }
        public decimal? sodiumNaMg { get; set; }
        public decimal? sulphurSMg { get; set; }
        public decimal? tinSnMcg { get; set; }
        public decimal? zincZnMg { get; set; }

        public decimal? retinolPreformedVitaminAMcg { get; set; }
        public decimal? alphaCaroteneMcg { get; set; }
        public decimal? betaCaroteneMcg { get; set; }
        public decimal? cryptoxanthinMcg { get; set; }
        public decimal? betaCaroteneEquivalentsProvitaminAMcg { get; set; }
        public decimal? vitaminARetinolEquivalentsMcg { get; set; }
        public decimal? luteinMcg { get; set; }
        public decimal? lycopeneMcg { get; set; }
        public decimal? xanthophylMcg { get; set; }
        public decimal? thiaminB1Mg { get; set; }
        public decimal? riboflavinB2Mg { get; set; }
        public decimal? niacinB3Mg { get; set; }
        public decimal? niacinDerivedFromTryptophanMg { get; set; }
        public decimal? niacinDerivedEquivalentsMg { get; set; }
        public decimal? pantothenicAcidB5Mg { get; set; }
        public decimal? pyridoxineB6Mg { get; set; }
        public decimal? biotinB7Mcg { get; set; }
        public decimal? cobalaminB12Mcg { get; set; }
        public decimal? folateNaturalMcg { get; set; }
        public decimal? folicAcidMcg { get; set; }
        public decimal? totalFolatesMcg { get; set; }
        public decimal? dietaryFolateEquivalentsMcg { get; set; }
        public decimal? vitaminCMg { get; set; }
        public decimal? cholecalciferolD3Mcg { get; set; }
        public decimal? ergocalciferolD2Mcg { get; set; }
        public decimal? n25HydroxyCholecalciferol25OhD3Mcg { get; set; }
        public decimal? n25HydroxyErgocalciferol25OhD2Mcg { get; set; }
        public decimal? vitaminD3EquivalentsMcg { get; set; }
        public decimal? alphaTocopherolMg { get; set; }
        public decimal? alphaTocotrienolMg { get; set; }
        public decimal? betaTocopherolMg { get; set; }
        public decimal? betaTocotrienolMg { get; set; }
        public decimal? deltaTocopherolMg { get; set; }
        public decimal? deltaTocotrienolMg { get; set; }
        public decimal? gammaTocopherolMg { get; set; }
        public decimal? gammaTocotrienolMg { get; set; }
        public decimal? vitaminEMg { get; set; }

        public decimal? c4PercentT { get; set; }
        public decimal? c6PercentT { get; set; }
        public decimal? c8PercentT { get; set; }
        public decimal? c10PercentT { get; set; }
        public decimal? c11PercentT { get; set; }
        public decimal? c12PercentT { get; set; }
        public decimal? c13PercentT { get; set; }
        public decimal? c14PercentT { get; set; }
        public decimal? c15PercentT { get; set; }
        public decimal? c16PercentT { get; set; }
        public decimal? c17PercentT { get; set; }
        public decimal? c18PercentT { get; set; }
        public decimal? c19PercentT { get; set; }
        public decimal? c20PercentT { get; set; }
        public decimal? c21PercentT { get; set; }
        public decimal? c22PercentT { get; set; }
        public decimal? c23PercentT { get; set; }
        public decimal? c24PercentT { get; set; }
        public decimal? totalSaturatedFattyAcidsEquatedPercentT { get; set; }
        public decimal? c121PercentT { get; set; }
        public decimal? c141PercentT { get; set; }
        public decimal? c151PercentT { get; set; }
        public decimal? c161PercentT { get; set; }
        public decimal? c171PercentT { get; set; }
        public decimal? c181PercentT { get; set; }
        public decimal? c181w7PercentT { get; set; }
        public decimal? c201PercentT { get; set; }
        public decimal? c201w11PercentT { get; set; }
        public decimal? c221PercentT { get; set; }
        public decimal? c221w11PercentT { get; set; }
        public decimal? c241PercentT { get; set; }
        public decimal? totalMonounsaturatedFattyAcidsEquatedPercentT { get; set; }
        public decimal? c122PercentT { get; set; }
        public decimal? c162w4PercentT { get; set; }
        public decimal? c163PercentT { get; set; }
        public decimal? c182w6PercentT { get; set; }
        public decimal? c183w3PercentT { get; set; }
        public decimal? c183w4PercentT { get; set; }
        public decimal? c183w6PercentT { get; set; }
        public decimal? c184w1PercentT { get; set; }
        public decimal? c184w3PercentT { get; set; }
        public decimal? c202PercentT { get; set; }
        public decimal? c202w6PercentT { get; set; }
        public decimal? c204PercentT { get; set; }
        public decimal? c203w3PercentT { get; set; }
        public decimal? c203w6PercentT { get; set; }
        public decimal? c204w3PercentT { get; set; }
        public decimal? c204w6PercentT { get; set; }
        public decimal? c205w3PercentT { get; set; }
        public decimal? c215w3PercentT { get; set; }
        public decimal? c222PercentT { get; set; }
        public decimal? c222w6PercentT { get; set; }
        public decimal? c224w6PercentT { get; set; }
        public decimal? c225w3PercentT { get; set; }
        public decimal? c225w6PercentT { get; set; }
        public decimal? c226w3PercentT { get; set; }
        public decimal? totalPolyunsaturatedFattyAcidsEquatedPercentT { get; set; }
        public decimal? totalLongChainOmega3FattyAcidsEquatedPercentT { get; set; }
        public decimal? totalUndifferentiatedFattyAcidsPercentT { get; set; }
        public decimal? totalTransFattyAcidsImputedPercentT { get; set; }

        public decimal? c4G { get; set; }
        public decimal? c6G { get; set; }
        public decimal? c8G { get; set; }
        public decimal? c10G { get; set; }
        public decimal? c11G { get; set; }
        public decimal? c12G { get; set; }
        public decimal? c13G { get; set; }
        public decimal? c14G { get; set; }
        public decimal? c15G { get; set; }
        public decimal? c16G { get; set; }
        public decimal? c17G { get; set; }
        public decimal? c18G { get; set; }
        public decimal? c19G { get; set; }
        public decimal? c20G { get; set; }
        public decimal? c21G { get; set; }
        public decimal? c22G { get; set; }
        public decimal? c23G { get; set; }
        public decimal? c24G { get; set; }
        public decimal? totalSaturatedFattyAcidsEquatedG { get; set; }
        public decimal? c121G { get; set; }
        public decimal? c141G { get; set; }
        public decimal? c151G { get; set; }
        public decimal? c161G { get; set; }
        public decimal? c171G { get; set; }
        public decimal? c181G { get; set; }
        public decimal? c181w7G { get; set; }
        public decimal? c201G { get; set; }
        public decimal? c201w11Mg { get; set; }
        public decimal? c221G { get; set; }
        public decimal? c221w11Mg { get; set; }
        public decimal? c241G { get; set; }
        public decimal? totalMonounsaturatedFattyAcidsEquatedG { get; set; }
        public decimal? c122G { get; set; }
        public decimal? c162w4Mg { get; set; }
        public decimal? c163G { get; set; }
        public decimal? c182w6G { get; set; }
        public decimal? c183w3G { get; set; }
        public decimal? c183w4G { get; set; }
        public decimal? c183w6Mg { get; set; }
        public decimal? c184w1G { get; set; }
        public decimal? c184w3Mg { get; set; }
        public decimal? c202Mg { get; set; }
        public decimal? c202w6Mg { get; set; }
        public decimal? c203Mg { get; set; }
        public decimal? c203w3Mg { get; set; }
        public decimal? c203w6Mg { get; set; }
        public decimal? c204G { get; set; }
        public decimal? c204w3Mg { get; set; }
        public decimal? c204w6Mg { get; set; }
        public decimal? c205w3Mg { get; set; }
        public decimal? c215w3G { get; set; }
        public decimal? c225w3Mg { get; set; }
        public decimal? c224w6Mg { get; set; }
        public decimal? c222G { get; set; }
        public decimal? c222w6Mg { get; set; }
        public decimal? c225w6G { get; set; }
        public decimal? c226w3Mg { get; set; }
        public decimal? totalPolyunsaturatedFattyAcidsEquatedG { get; set; }
        public decimal? totalLongChainOmega3FattyAcidsEquatedMg { get; set; }
        public decimal? totalUndifferentiatedFattyAcidsMassBasisMg { get; set; }
        public decimal? totalTransFattyAcidsImputedMg { get; set; }

        public decimal? caffeineMg { get; set; }
        public decimal? cholesterolMg { get; set; }

        public decimal? alanineMgPerGN { get; set; }
        public decimal? arginineMgPerGN { get; set; }
        public decimal? asparticAcidMgPerGN { get; set; }
        public decimal? cystinePlusCysteineMgPerGN { get; set; }
        public decimal? glutamicAcidMgPerGN { get; set; }
        public decimal? glycineMgPerGN { get; set; }
        public decimal? histidineMgPerGN { get; set; }
        public decimal? isoleucineMgPerGN { get; set; }
        public decimal? leucineMgPerGN { get; set; }
        public decimal? lysineMgPerGN { get; set; }
        public decimal? methionineMgPerGN { get; set; }
        public decimal? phenylalanineMgPerGN { get; set; }
        public decimal? prolineMgPerGN { get; set; }
        public decimal? serineMgPerGN { get; set; }
        public decimal? threonineMgPerGN { get; set; }
        public decimal? tyrosineMgPerGN { get; set; }
        public decimal? tryptophanMgPerGN { get; set; }
        public decimal? valineMgPerGN { get; set; }

        public decimal? alanineMg { get; set; }
        public decimal? arginineMg { get; set; }
        public decimal? asparticAcidMg { get; set; }
        public decimal? cystinePlusCysteineMg { get; set; }
        public decimal? glutamicAcidMg { get; set; }
        public decimal? glycineMg { get; set; }
        public decimal? histidineMg { get; set; }
        public decimal? isoleucineMg { get; set; }
        public decimal? leucineMg { get; set; }
        public decimal? lysineMg { get; set; }
        public decimal? methionineMg { get; set; }
        public decimal? phenylalanineMg { get; set; }
        public decimal? prolineMg { get; set; }
        public decimal? serineMg { get; set; }
        public decimal? threonineMg { get; set; }
        public decimal? tyrosineMg { get; set; }
        public decimal? tryptophanMg { get; set; }
        public decimal? valineMg { get; set; }
    }
}
