using System;
using System.Collections.Generic;
using System.Text;

namespace FitnessTool
{
    internal class AfcdFoodEntryRaw
    {

        public string PublicFoodKey { get; set; } = "";
        public string ClassificationID { get; set; } = "";
        public string Derivation { get; set; } = "";
        public string FoodName { get; set; } = "";

        public decimal? EnergyWithDietaryFibreEquatedKj { get; set; }
        public decimal? EnergyWithoutDietaryFibreEquatedKj { get; set; }
        public decimal? MoistureG { get; set; }
        public decimal? ProteinG { get; set; }
        public decimal? NitrogenG { get; set; }
        public decimal? FatTotalG { get; set; }
        public decimal? AshG { get; set; }
        public decimal? TotalDietaryFibreG { get; set; }
        public decimal? AlcoholG { get; set; }
        public decimal? FructoseG { get; set; }
        public decimal? GlucoseG { get; set; }
        public decimal? SucroseG { get; set; }
        public decimal? MaltoseG { get; set; }
        public decimal? LactoseG { get; set; }
        public decimal? GalactoseG { get; set; }
        public decimal? TotalSugarsG { get; set; }
        public decimal? AddedSugarsG { get; set; }
        public decimal? FreeSugarsG { get; set; }
        public decimal? StarchG { get; set; }
        public decimal? DextrinG { get; set; }
        public decimal? GlycerolG { get; set; }
        public decimal? GlycogenG { get; set; }
        public decimal? InulinG { get; set; }
        public decimal? ErythritolG { get; set; }
        public decimal? MaltitolG { get; set; }
        public decimal? MannitolG { get; set; }
        public decimal? XylitolG { get; set; }
        public decimal? MaltodextrinG { get; set; }
        public decimal? OligosaccharidesG { get; set; }
        public decimal? PolydextroseG { get; set; }
        public decimal? RaffinoseG { get; set; }
        public decimal? StachyoseG { get; set; }
        public decimal? SorbitolG { get; set; }
        public decimal? ResistantStarchG { get; set; }
        public decimal? AvailableCarbohydrateWithoutSugarAlcoholsG { get; set; }
        public decimal? AvailableCarbohydrateWithSugarAlcoholsG { get; set; }

        public decimal? AceticAcidG { get; set; }
        public decimal? CitricAcidG { get; set; }
        public decimal? FumaricAcidG { get; set; }
        public decimal? LacticAcidG { get; set; }
        public decimal? MalicAcidG { get; set; }
        public decimal? OxalicAcidG { get; set; }
        public decimal? PropionicAcidG { get; set; }
        public decimal? QuinicAcidG { get; set; }
        public decimal? ShikimicAcidG { get; set; }
        public decimal? SuccinicAcidG { get; set; }
        public decimal? TartaricAcidG { get; set; }

        public decimal? AluminiumAlMcg { get; set; }
        public decimal? AntimonySbMcg { get; set; }
        public decimal? ArsenicAsMcg { get; set; }
        public decimal? CadmiumCdMcg { get; set; }
        public decimal? CalciumCaMg { get; set; }
        public decimal? ChromiumCrMcg { get; set; }
        public decimal? ChlorideClMg { get; set; }
        public decimal? CobaltCoMcg { get; set; }
        public decimal? CopperCuMg { get; set; }
        public decimal? FluorideFMcg { get; set; }
        public decimal? IodineIMcg { get; set; }
        public decimal? IronFeMg { get; set; }
        public decimal? LeadPbMcg { get; set; }
        public decimal? MagnesiumMgMg { get; set; }
        public decimal? ManganeseMnMg { get; set; }
        public decimal? MercuryHgMcg { get; set; }
        public decimal? MolybdenumMoMcg { get; set; }
        public decimal? NickelNiMcg { get; set; }
        public decimal? PhosphorusPMg { get; set; }
        public decimal? PotassiumKMg { get; set; }
        public decimal? SeleniumSeMcg { get; set; }
        public decimal? SodiumNaMg { get; set; }
        public decimal? SulphurSMg { get; set; }
        public decimal? TinSnMcg { get; set; }
        public decimal? ZincZnMg { get; set; }

        public decimal? RetinolPreformedVitaminAMcg { get; set; }
        public decimal? AlphaCaroteneMcg { get; set; }
        public decimal? BetaCaroteneMcg { get; set; }
        public decimal? CryptoxanthinMcg { get; set; }
        public decimal? BetaCaroteneEquivalentsProvitaminAMcg { get; set; }
        public decimal? VitaminARetinolEquivalentsMcg { get; set; }
        public decimal? LuteinMcg { get; set; }
        public decimal? LycopeneMcg { get; set; }
        public decimal? XanthophylMcg { get; set; }
        public decimal? ThiaminB1Mg { get; set; }
        public decimal? RiboflavinB2Mg { get; set; }
        public decimal? NiacinB3Mg { get; set; }
        public decimal? NiacinDerivedFromTryptophanMg { get; set; }
        public decimal? NiacinDerivedEquivalentsMg { get; set; }
        public decimal? PantothenicAcidB5Mg { get; set; }
        public decimal? PyridoxineB6Mg { get; set; }
        public decimal? BiotinB7Mcg { get; set; }
        public decimal? CobalaminB12Mcg { get; set; }
        public decimal? FolateNaturalMcg { get; set; }
        public decimal? FolicAcidMcg { get; set; }
        public decimal? TotalFolatesMcg { get; set; }
        public decimal? DietaryFolateEquivalentsMcg { get; set; }
        public decimal? VitaminCMg { get; set; }
        public decimal? CholecalciferolD3Mcg { get; set; }
        public decimal? ErgocalciferolD2Mcg { get; set; }
        public decimal? N25HydroxyCholecalciferol25OhD3Mcg { get; set; }
        public decimal? N25HydroxyErgocalciferol25OhD2Mcg { get; set; }
        public decimal? VitaminD3EquivalentsMcg { get; set; }
        public decimal? AlphaTocopherolMg { get; set; }
        public decimal? AlphaTocotrienolMg { get; set; }
        public decimal? BetaTocopherolMg { get; set; }
        public decimal? BetaTocotrienolMg { get; set; }
        public decimal? DeltaTocopherolMg { get; set; }
        public decimal? DeltaTocotrienolMg { get; set; }
        public decimal? GammaTocopherolMg { get; set; }
        public decimal? GammaTocotrienolMg { get; set; }
        public decimal? VitaminEMg { get; set; }

        public decimal? C4PercentT { get; set; }
        public decimal? C6PercentT { get; set; }
        public decimal? C8PercentT { get; set; }
        public decimal? C10PercentT { get; set; }
        public decimal? C11PercentT { get; set; }
        public decimal? C12PercentT { get; set; }
        public decimal? C13PercentT { get; set; }
        public decimal? C14PercentT { get; set; }
        public decimal? C15PercentT { get; set; }
        public decimal? C16PercentT { get; set; }
        public decimal? C17PercentT { get; set; }
        public decimal? C18PercentT { get; set; }
        public decimal? C19PercentT { get; set; }
        public decimal? C20PercentT { get; set; }
        public decimal? C21PercentT { get; set; }
        public decimal? C22PercentT { get; set; }
        public decimal? C23PercentT { get; set; }
        public decimal? C24PercentT { get; set; }
        public decimal? TotalSaturatedFattyAcidsEquatedPercentT { get; set; }
        public decimal? C121PercentT { get; set; }
        public decimal? C141PercentT { get; set; }
        public decimal? C151PercentT { get; set; }
        public decimal? C161PercentT { get; set; }
        public decimal? C171PercentT { get; set; }
        public decimal? C181PercentT { get; set; }
        public decimal? C181w7PercentT { get; set; }
        public decimal? C201PercentT { get; set; }
        public decimal? C201w11PercentT { get; set; }
        public decimal? C221PercentT { get; set; }
        public decimal? C221w11PercentT { get; set; }
        public decimal? C241PercentT { get; set; }
        public decimal? TotalMonounsaturatedFattyAcidsEquatedPercentT { get; set; }
        public decimal? C122PercentT { get; set; }
        public decimal? C162w4PercentT { get; set; }
        public decimal? C163PercentT { get; set; }
        public decimal? C182w6PercentT { get; set; }
        public decimal? C183w3PercentT { get; set; }
        public decimal? C183w4PercentT { get; set; }
        public decimal? C183w6PercentT { get; set; }
        public decimal? C184w1PercentT { get; set; }
        public decimal? C184w3PercentT { get; set; }
        public decimal? C202PercentT { get; set; }
        public decimal? C202w6PercentT { get; set; }
        public decimal? C204PercentT { get; set; }
        public decimal? C203w3PercentT { get; set; }
        public decimal? C203w6PercentT { get; set; }
        public decimal? C204w3PercentT { get; set; }
        public decimal? C204w6PercentT { get; set; }
        public decimal? C205w3PercentT { get; set; }
        public decimal? C215w3PercentT { get; set; }
        public decimal? C222PercentT { get; set; }
        public decimal? C222w6PercentT { get; set; }
        public decimal? C224w6PercentT { get; set; }
        public decimal? C225w3PercentT { get; set; }
        public decimal? C225w6PercentT { get; set; }
        public decimal? C226w3PercentT { get; set; }
        public decimal? TotalPolyunsaturatedFattyAcidsEquatedPercentT { get; set; }
        public decimal? TotalLongChainOmega3FattyAcidsEquatedPercentT { get; set; }
        public decimal? TotalUndifferentiatedFattyAcidsPercentT { get; set; }
        public decimal? TotalTransFattyAcidsImputedPercentT { get; set; }

        public decimal? C4G { get; set; }
        public decimal? C6G { get; set; }
        public decimal? C8G { get; set; }
        public decimal? C10G { get; set; }
        public decimal? C11G { get; set; }
        public decimal? C12G { get; set; }
        public decimal? C13G { get; set; }
        public decimal? C14G { get; set; }
        public decimal? C15G { get; set; }
        public decimal? C16G { get; set; }
        public decimal? C17G { get; set; }
        public decimal? C18G { get; set; }
        public decimal? C19G { get; set; }
        public decimal? C20G { get; set; }
        public decimal? C21G { get; set; }
        public decimal? C22G { get; set; }
        public decimal? C23G { get; set; }
        public decimal? C24G { get; set; }
        public decimal? TotalSaturatedFattyAcidsEquatedG { get; set; }
        public decimal? C121G { get; set; }
        public decimal? C141G { get; set; }
        public decimal? C151G { get; set; }
        public decimal? C161G { get; set; }
        public decimal? C171G { get; set; }
        public decimal? C181G { get; set; }
        public decimal? C181w7G { get; set; }
        public decimal? C201G { get; set; }
        public decimal? C201w11Mg { get; set; }
        public decimal? C221G { get; set; }
        public decimal? C221w11Mg { get; set; }
        public decimal? C241G { get; set; }
        public decimal? TotalMonounsaturatedFattyAcidsEquatedG { get; set; }
        public decimal? C122G { get; set; }
        public decimal? C162w4Mg { get; set; }
        public decimal? C163G { get; set; }
        public decimal? C182w6G { get; set; }
        public decimal? C183w3G { get; set; }
        public decimal? C183w4G { get; set; }
        public decimal? C183w6Mg { get; set; }
        public decimal? C184w1G { get; set; }
        public decimal? C184w3Mg { get; set; }
        public decimal? C202Mg { get; set; }
        public decimal? C202w6Mg { get; set; }
        public decimal? C203Mg { get; set; }
        public decimal? C203w3Mg { get; set; }
        public decimal? C203w6Mg { get; set; }
        public decimal? C204G { get; set; }
        public decimal? C204w3Mg { get; set; }
        public decimal? C204w6Mg { get; set; }
        public decimal? C205w3Mg { get; set; }
        public decimal? C215w3G { get; set; }
        public decimal? C225w3Mg { get; set; }
        public decimal? C224w6Mg { get; set; }
        public decimal? C222G { get; set; }
        public decimal? C222w6Mg { get; set; }
        public decimal? C225w6G { get; set; }
        public decimal? C226w3Mg { get; set; }
        public decimal? TotalPolyunsaturatedFattyAcidsEquatedG { get; set; }
        public decimal? TotalLongChainOmega3FattyAcidsEquatedMg { get; set; }
        public decimal? TotalUndifferentiatedFattyAcidsMassBasisMg { get; set; }
        public decimal? TotalTransFattyAcidsImputedMg { get; set; }

        public decimal? CaffeineMg { get; set; }
        public decimal? CholesterolMg { get; set; }

        public decimal? AlanineMgPerGN { get; set; }
        public decimal? ArginineMgPerGN { get; set; }
        public decimal? AsparticAcidMgPerGN { get; set; }
        public decimal? CystinePlusCysteineMgPerGN { get; set; }
        public decimal? GlutamicAcidMgPerGN { get; set; }
        public decimal? GlycineMgPerGN { get; set; }
        public decimal? HistidineMgPerGN { get; set; }
        public decimal? IsoleucineMgPerGN { get; set; }
        public decimal? LeucineMgPerGN { get; set; }
        public decimal? LysineMgPerGN { get; set; }
        public decimal? MethionineMgPerGN { get; set; }
        public decimal? PhenylalanineMgPerGN { get; set; }
        public decimal? ProlineMgPerGN { get; set; }
        public decimal? SerineMgPerGN { get; set; }
        public decimal? ThreonineMgPerGN { get; set; }
        public decimal? TyrosineMgPerGN { get; set; }
        public decimal? TryptophanMgPerGN { get; set; }
        public decimal? ValineMgPerGN { get; set; }

        public decimal? AlanineMg { get; set; }
        public decimal? ArginineMg { get; set; }
        public decimal? AsparticAcidMg { get; set; }
        public decimal? CystinePlusCysteineMg { get; set; }
        public decimal? GlutamicAcidMg { get; set; }
        public decimal? GlycineMg { get; set; }
        public decimal? HistidineMg { get; set; }
        public decimal? IsoleucineMg { get; set; }
        public decimal? LeucineMg { get; set; }
        public decimal? LysineMg { get; set; }
        public decimal? MethionineMg { get; set; }
        public decimal? PhenylalanineMg { get; set; }
        public decimal? ProlineMg { get; set; }
        public decimal? SerineMg { get; set; }
        public decimal? ThreonineMg { get; set; }
        public decimal? TyrosineMg { get; set; }
        public decimal? TryptophanMg { get; set; }
        public decimal? ValineMg { get; set; }
    }
}
